//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartHup.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Labels {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Labels() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SmartHup.Resources.Labels", typeof(Labels).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        public static string actionId {
            get {
                return ResourceManager.GetString("actionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Data.
        /// </summary>
        public static string clientData {
            get {
                return ResourceManager.GetString("clientData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created By.
        /// </summary>
        public static string createdBy {
            get {
                return ResourceManager.GetString("createdBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Added.
        /// </summary>
        public static string creationDate {
            get {
                return ResourceManager.GetString("creationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted By.
        /// </summary>
        public static string deletedBy {
            get {
                return ResourceManager.GetString("deletedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Deleted.
        /// </summary>
        public static string deletedDate {
            get {
                return ResourceManager.GetString("deletedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English Name.
        /// </summary>
        public static string EName {
            get {
                return ResourceManager.GetString("EName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string ID {
            get {
                return ResourceManager.GetString("ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Locked ? .
        /// </summary>
        public static string isLocked {
            get {
                return ResourceManager.GetString("isLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Parent.
        /// </summary>
        public static string isParent {
            get {
                return ResourceManager.GetString("isParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is SSL Exist.
        /// </summary>
        public static string isSslExist {
            get {
                return ResourceManager.GetString("isSslExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Data.
        /// </summary>
        public static string logData {
            get {
                return ResourceManager.GetString("logData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Modified.
        /// </summary>
        public static string modificationDate {
            get {
                return ResourceManager.GetString("modificationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modified By.
        /// </summary>
        public static string modifiedBy {
            get {
                return ResourceManager.GetString("modifiedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module.
        /// </summary>
        public static string moduleId {
            get {
                return ResourceManager.GetString("moduleId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent Id.
        /// </summary>
        public static string parentId {
            get {
                return ResourceManager.GetString("parentId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Precheck Required.
        /// </summary>
        public static string precheckRquired {
            get {
                return ResourceManager.GetString("precheckRquired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precheck Service.
        /// </summary>
        public static string precheckServiceId {
            get {
                return ResourceManager.GetString("precheckServiceId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember Me ?.
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string RoleId {
            get {
                return ResourceManager.GetString("RoleId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Configure.
        /// </summary>
        public static string serviceConfigurationId {
            get {
                return ResourceManager.GetString("serviceConfigurationId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string serviceDescription {
            get {
                return ResourceManager.GetString("serviceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English Label.
        /// </summary>
        public static string ServiceELable {
            get {
                return ResourceManager.GetString("ServiceELable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English Name.
        /// </summary>
        public static string serviceEName {
            get {
                return ResourceManager.GetString("serviceEName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string serviceHanlerId {
            get {
                return ResourceManager.GetString("serviceHanlerId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Handler Name.
        /// </summary>
        public static string serviceHanlerName {
            get {
                return ResourceManager.GetString("serviceHanlerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SH-Status.
        /// </summary>
        public static string serviceHanlerStatus {
            get {
                return ResourceManager.GetString("serviceHanlerStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept Encoding.
        /// </summary>
        public static string serviceHostAcceptEncoding {
            get {
                return ResourceManager.GetString("serviceHostAcceptEncoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charset.
        /// </summary>
        public static string serviceHostCharSet {
            get {
                return ResourceManager.GetString("serviceHostCharSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content Type.
        /// </summary>
        public static string serviceHostContentType {
            get {
                return ResourceManager.GetString("serviceHostContentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encryption Method.
        /// </summary>
        public static string serviceHostEncryptionMethod {
            get {
                return ResourceManager.GetString("serviceHostEncryptionMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integration Type.
        /// </summary>
        public static string serviceHostIntegrationType {
            get {
                return ResourceManager.GetString("serviceHostIntegrationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public Key.
        /// </summary>
        public static string serviceHostPublicKey {
            get {
                return ResourceManager.GetString("serviceHostPublicKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host URI.
        /// </summary>
        public static string serviceHostUri {
            get {
                return ResourceManager.GetString("serviceHostUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to service.
        /// </summary>
        public static string serviceId {
            get {
                return ResourceManager.GetString("serviceId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Label.
        /// </summary>
        public static string ServiceLable {
            get {
                return ResourceManager.GetString("ServiceLable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string serviceName {
            get {
                return ResourceManager.GetString("serviceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English Label.
        /// </summary>
        public static string serviceProviderELabel {
            get {
                return ResourceManager.GetString("serviceProviderELabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English Name.
        /// </summary>
        public static string serviceProviderEName {
            get {
                return ResourceManager.GetString("serviceProviderEName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Provider.
        /// </summary>
        public static string serviceProviderId {
            get {
                return ResourceManager.GetString("serviceProviderId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Label.
        /// </summary>
        public static string serviceProviderLabel {
            get {
                return ResourceManager.GetString("serviceProviderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string serviceProviderName {
            get {
                return ResourceManager.GetString("serviceProviderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP-Status.
        /// </summary>
        public static string serviceProviderStatus {
            get {
                return ResourceManager.GetString("serviceProviderStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SP Type.
        /// </summary>
        public static string serviceProviderTypeId {
            get {
                return ResourceManager.GetString("serviceProviderTypeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Scenario.
        /// </summary>
        public static string serviceScenarioId {
            get {
                return ResourceManager.GetString("serviceScenarioId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S-Status.
        /// </summary>
        public static string serviceStatus {
            get {
                return ResourceManager.GetString("serviceStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string status {
            get {
                return ResourceManager.GetString("status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string userId {
            get {
                return ResourceManager.GetString("userId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string version {
            get {
                return ResourceManager.GetString("version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
