//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartHup.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACCOUNT
    {
        public decimal SystemId { get; set; }
        public Nullable<int> Version { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
        public string mbr { get; set; }
        public string PAN { get; set; }
        public string expDate { get; set; }
        public string cardCreateDate { get; set; }
        public string panCategory { get; set; }
        public string bankAccountNumber { get; set; }
        public string bankAccountType { get; set; }
        public string bankBranchId { get; set; }
        public Nullable<long> bankId { get; set; }
        public Nullable<int> idx { get; set; }
        public Nullable<long> customerIdNumber { get; set; }
        public string accountName { get; set; }
        public string account1 { get; set; }
        public Nullable<decimal> accountId { get; set; }
        public int paymentMethodId { get; set; }
        public string paymentMethodLabel { get; set; }
        public Nullable<int> isDefault { get; set; }
        public int isActive { get; set; }
        public string entityType { get; set; }
        public string entityId { get; set; }
        public int status { get; set; }
    
        public virtual Bank Bank { get; set; }
        public virtual customer customer { get; set; }
        public virtual EntityStatus EntityStatus { get; set; }
    }
}
