//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartHup.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ALERTLEVEL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ALERTLEVEL()
        {
            this.ALERT = new HashSet<ALERT>();
        }
    
        public decimal systemId { get; set; }
        public int Version { get; set; }
        public string STATUS { get; set; }
        public string Notes { get; set; }
        public Nullable<long> JOBID { get; set; }
        public Nullable<decimal> MINTHRESHOLD { get; set; }
        public string regex { get; set; }
        public Nullable<decimal> MAXTHRESHOLD { get; set; }
        public string ALERTLEVEL1 { get; set; }
        public Nullable<int> entityStatus_systemId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ALERT> ALERT { get; set; }
        public virtual EntityStatus EntityStatus { get; set; }
        public virtual MONITORINGJOB MONITORINGJOB { get; set; }
    }
}
