//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartHup.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ALERT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ALERT()
        {
            this.MONITORINGLOG = new HashSet<MONITORINGLOG>();
        }
    
        public long systemId { get; set; }
        public int Version { get; set; }
        public string STATUS { get; set; }
        public string Notes { get; set; }
        public Nullable<decimal> ALERTLEVEL { get; set; }
        public string ALERTMESSAGE { get; set; }
        public string ALERTMEDIUM { get; set; }
        public string RECEIVERNAME { get; set; }
        public string RECEIVERADDRESS { get; set; }
        public Nullable<long> userId { get; set; }
        public Nullable<long> spId { get; set; }
        public Nullable<long> roleId { get; set; }
        public Nullable<long> notificationCategoryId { get; set; }
        public Nullable<int> entityStatus_systemId { get; set; }
    
        public virtual ALERTLEVEL ALERTLEVEL1 { get; set; }
        public virtual EntityStatus EntityStatus { get; set; }
        public virtual NotificationCategory NotificationCategory { get; set; }
        public virtual Role Role { get; set; }
        public virtual ServiceProvider ServiceProvider { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MONITORINGLOG> MONITORINGLOG { get; set; }
    }
}
