//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartHup.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Announcement
    {
        public long systemId { get; set; }
        public string AnnouncementTitle { get; set; }
        public string AnnouncementArTitle { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<long> UserGroup_ID { get; set; }
        public long Company_ID { get; set; }
        public Nullable<System.DateTime> creationDate { get; set; }
        public Nullable<System.DateTime> deletedDate { get; set; }
        public Nullable<System.DateTime> modificationDate { get; set; }
        public Nullable<long> createdBy { get; set; }
        public Nullable<long> deletedBy { get; set; }
        public Nullable<long> modifiedBy { get; set; }
        public Nullable<int> version { get; set; }
        public Nullable<int> entityStatus_systemId { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual EntityStatu EntityStatu { get; set; }
        public virtual UserGroup UserGroup { get; set; }
    }
}
