//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartHup.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuditingLog
    {
        public long systemId { get; set; }
        public Nullable<long> userId { get; set; }
        public long actionId { get; set; }
        public long moduleId { get; set; }
        public string oldData { get; set; }
        public System.DateTime dateCreated { get; set; }
        public string clientData { get; set; }
    
        public virtual Action Action { get; set; }
        public virtual Module Module { get; set; }
        public virtual User User { get; set; }
    }
}
