//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartHup.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class branches
    {
        public decimal SystemId { get; set; }
        public int Version { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> Note { get; set; }
        public string branchId { get; set; }
        public string branchName { get; set; }
        public decimal bankId { get; set; }
        public Nullable<int> idx { get; set; }
    }
}
