//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartHup.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChatSession
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ChatSession()
        {
            this.OnlineUsers = new HashSet<OnlineUser>();
        }
    
        public long systemId { get; set; }
        public long SubmitterUser { get; set; }
        public Nullable<long> TicketId { get; set; }
        public long ChatQueue { get; set; }
        public Nullable<long> AssignedUser { get; set; }
        public Nullable<System.DateTime> start_time { get; set; }
        public Nullable<System.DateTime> end_time { get; set; }
        public Nullable<System.DateTime> acceptTime { get; set; }
        public string ChatStatus { get; set; }
    
        public virtual ChatSetting ChatSetting { get; set; }
        public virtual Ticket Ticket { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OnlineUser> OnlineUsers { get; set; }
    }
}
