//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartHup.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contracts
    {
        public long systemId { get; set; }
        public long ContractType { get; set; }
        public long ServiceProvider { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public string Terms { get; set; }
        public int Fees { get; set; }
        public bool SlaEnabled { get; set; }
        public long Account { get; set; }
        public int ContractStatus { get; set; }
        public System.DateTime creationDate { get; set; }
        public Nullable<System.DateTime> modificationDate { get; set; }
        public Nullable<System.DateTime> deletedDate { get; set; }
        public Nullable<int> version { get; set; }
        public Nullable<long> createdBy { get; set; }
        public Nullable<long> modifiedBy { get; set; }
        public Nullable<long> deletedBy { get; set; }
    
        public virtual ContractTypes ContractTypes { get; set; }
        public virtual EntityStatus EntityStatus { get; set; }
        public virtual ServiceProvider ServiceProvider1 { get; set; }
        public virtual User User { get; set; }
    }
}
