//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartHup.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CurrentSlaResult
    {
        public long systemId { get; set; }
        public Nullable<long> MeasurementId { get; set; }
        public Nullable<double> currenetResult { get; set; }
        public Nullable<double> SLAGrade { get; set; }
        public Nullable<double> internalGrade { get; set; }
        public Nullable<System.DateTime> runDate { get; set; }
        public Nullable<bool> finalResult { get; set; }
    }
}
