//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartHup.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public customer()
        {
            this.ACCOUNT = new HashSet<ACCOUNT>();
            this.Favourite = new HashSet<Favourite>();
        }
    
        public long SystemId { get; set; }
        public int Version { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
        public string phoneNo { get; set; }
        public string email { get; set; }
        public string fullName { get; set; }
        public string dateOfBirth { get; set; }
        public string job { get; set; }
        public string customerIdNumber { get; set; }
        public string customerIdType { get; set; }
        public Nullable<int> idx { get; set; }
        public string userName { get; set; }
        public string password { get; set; }
        public string IMEI { get; set; }
        public string address { get; set; }
        public string otpPassword { get; set; }
        public Nullable<long> otpLastDate { get; set; }
        public Nullable<long> otpStartDate { get; set; }
        public string activationCode { get; set; }
        public Nullable<int> isActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ACCOUNT> ACCOUNT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Favourite> Favourite { get; set; }
    }
}
