//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartHup.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DueDateRule
    {
        public long systemId { get; set; }
        public string DueDateRuleName { get; set; }
        public Nullable<long> Category_ID { get; set; }
        public Nullable<long> Urgancy_ID { get; set; }
        public Nullable<long> Priority_ID { get; set; }
        public Nullable<long> SLA_ID { get; set; }
        public Nullable<int> DueDate { get; set; }
        public System.DateTime creationDate { get; set; }
        public Nullable<System.DateTime> modificationDate { get; set; }
        public long createdBy { get; set; }
        public Nullable<long> modifiedBy { get; set; }
        public Nullable<int> version { get; set; }
        public Nullable<int> entityStatus_systemId { get; set; }
        public Nullable<long> SubCategory { get; set; }
        public Nullable<System.DateTime> deletedDate { get; set; }
        public Nullable<long> deletedBy { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Category Category1 { get; set; }
        public virtual EntityStatu EntityStatu { get; set; }
        public virtual Priority Priority { get; set; }
        public virtual SLA SLA { get; set; }
        public virtual Urgency Urgency { get; set; }
    }
}
