//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartHup.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EscalationRule
    {
        public long systemId { get; set; }
        public string EscalationName { get; set; }
        public string EscalationArName { get; set; }
        public Nullable<long> Category_ID { get; set; }
        public Nullable<long> Sub_Category_ID { get; set; }
        public Nullable<long> SLA_ID { get; set; }
        public Nullable<long> Status_ID { get; set; }
        public Nullable<long> Priority_ID { get; set; }
        public Nullable<long> ChangePriority { get; set; }
        public Nullable<long> ChangeStatus { get; set; }
        public Nullable<long> ReAssignUser { get; set; }
        public Nullable<long> AssignedUser_ID { get; set; }
        public Nullable<long> SubmitterUSerID { get; set; }
        public Nullable<int> EscalationLevel { get; set; }
        public Nullable<long> AssignedGroup { get; set; }
        public Nullable<System.DateTime> creationDate { get; set; }
        public Nullable<System.DateTime> modificationDate { get; set; }
        public Nullable<long> createdBy { get; set; }
        public Nullable<long> modifiedBy { get; set; }
        public Nullable<int> version { get; set; }
        public Nullable<int> entityStatus_systemId { get; set; }
        public Nullable<System.DateTime> deletedDate { get; set; }
        public Nullable<long> deletedBy { get; set; }
        public Nullable<long> TimerID { get; set; }
        public Nullable<int> Hours { get; set; }
        public Nullable<int> Minutes { get; set; }
        public string FromDueDate { get; set; }
        public string FromTimer { get; set; }
        public string Escalate { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Category Category1 { get; set; }
        public virtual EntityStatu EntityStatu { get; set; }
        public virtual Priority Priority { get; set; }
        public virtual Priority Priority1 { get; set; }
        public virtual SLA SLA { get; set; }
        public virtual Status Status { get; set; }
        public virtual Status Status1 { get; set; }
        public virtual Timer Timer { get; set; }
        public virtual UserGroup UserGroup { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual User User2 { get; set; }
    }
}
