//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartHup.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Favourite
    {
        public string favoriteId { get; set; }
        public string favoriteValue { get; set; }
        public string favoriteName { get; set; }
        public Nullable<int> Version { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
        public Nullable<int> favoriteStatus { get; set; }
        public Nullable<int> idx { get; set; }
        public Nullable<long> customer { get; set; }
        public Nullable<decimal> systemId { get; set; }
    
        public virtual customer customer1 { get; set; }
    }
}
