//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartHup.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KnowledgeBase
    {
        public long systemId { get; set; }
        public string TopicName { get; set; }
        public string TopicArName { get; set; }
        public Nullable<long> Category_ID { get; set; }
        public Nullable<long> Sub_Category_ID { get; set; }
        public Nullable<long> User_ID { get; set; }
        public string Quetion { get; set; }
        public string Answer { get; set; }
        public byte[] Attachment { get; set; }
        public Nullable<bool> Publish { get; set; }
        public Nullable<long> createdBy { get; set; }
        public Nullable<long> modifiedBy { get; set; }
        public Nullable<System.DateTime> creationDate { get; set; }
        public Nullable<System.DateTime> modificationDate { get; set; }
        public Nullable<int> entityStatus_systemId { get; set; }
        public Nullable<int> version { get; set; }
        public Nullable<System.DateTime> deletedDate { get; set; }
        public Nullable<long> deletedBy { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual EntityStatu EntityStatu { get; set; }
        public virtual User User { get; set; }
    }
}
