//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartHup.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Measurment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Measurment()
        {
            this.CurrentMeasurementLists = new HashSet<CurrentMeasurementList>();
        }
    
        public long systemId { get; set; }
        public string MeasurmentName { get; set; }
        public string MeasurmentArName { get; set; }
        public string Unit { get; set; }
        public string Formula { get; set; }
        public Nullable<long> SLAId { get; set; }
        public Nullable<long> MeasurmentList_ID { get; set; }
        public Nullable<int> TestInterval { get; set; }
        public string CurrentValue { get; set; }
        public Nullable<System.DateTime> creationDate { get; set; }
        public Nullable<System.DateTime> modificationDate { get; set; }
        public Nullable<long> createdBy { get; set; }
        public Nullable<long> modifiedBy { get; set; }
        public Nullable<int> version { get; set; }
        public Nullable<int> entityStatus_systemId { get; set; }
        public Nullable<long> MeasurmentList_ID2 { get; set; }
        public Nullable<int> critical_grade { get; set; }
        public Nullable<int> warning_grade { get; set; }
        public Nullable<int> optimum_grade { get; set; }
        public Nullable<int> goal_critical { get; set; }
        public Nullable<int> goal_warning { get; set; }
        public Nullable<int> goal_optimum { get; set; }
        public Nullable<int> sla_critical { get; set; }
        public Nullable<int> sla_warning { get; set; }
        public Nullable<int> sla_optimum { get; set; }
        public Nullable<bool> calculated { get; set; }
        public Nullable<System.DateTime> deletedDate { get; set; }
        public Nullable<long> deletedBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CurrentMeasurementList> CurrentMeasurementLists { get; set; }
        public virtual EntityStatu EntityStatu { get; set; }
        public virtual MeasurmentList MeasurmentList { get; set; }
        public virtual MeasurmentList MeasurmentList1 { get; set; }
        public virtual SLA SLA { get; set; }
    }
}
