//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartHup.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TicketsEntities : DbContext
    {
        public TicketsEntities()
            : base("name=TicketsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Action> Actions { get; set; }
        public virtual DbSet<Announcement> Announcements { get; set; }
        public virtual DbSet<Attachement> Attachements { get; set; }
        public virtual DbSet<AuditingLog> AuditingLogs { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<CategoryType> CategoryTypes { get; set; }
        public virtual DbSet<ChatSession> ChatSessions { get; set; }
        public virtual DbSet<ChatSetting> ChatSettings { get; set; }
        public virtual DbSet<Company> Companies { get; set; }
        public virtual DbSet<Company_Announcement> Company_Announcement { get; set; }
        public virtual DbSet<CurrentMeasurementList> CurrentMeasurementLists { get; set; }
        public virtual DbSet<CurrentSlaResult> CurrentSlaResults { get; set; }
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<DueDateRule> DueDateRules { get; set; }
        public virtual DbSet<EntityStatu> EntityStatus { get; set; }
        public virtual DbSet<EscalationRule> EscalationRules { get; set; }
        public virtual DbSet<GroupType> GroupTypes { get; set; }
        public virtual DbSet<Impact> Impacts { get; set; }
        public virtual DbSet<KnowledgeBase> KnowledgeBases { get; set; }
        public virtual DbSet<Measurment> Measurments { get; set; }
        public virtual DbSet<MeasurmentList> MeasurmentLists { get; set; }
        public virtual DbSet<Module> Modules { get; set; }
        public virtual DbSet<OnlineUser> OnlineUsers { get; set; }
        public virtual DbSet<OperatingTime> OperatingTimes { get; set; }
        public virtual DbSet<Priority> Priorities { get; set; }
        public virtual DbSet<PriorityMatrix> PriorityMatrices { get; set; }
        public virtual DbSet<PriorityRule> PriorityRules { get; set; }
        public virtual DbSet<Reminder> Reminders { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<RoleAction> RoleActions { get; set; }
        public virtual DbSet<RoutingRule> RoutingRules { get; set; }
        public virtual DbSet<Section> Sections { get; set; }
        public virtual DbSet<ShareTopic> ShareTopics { get; set; }
        public virtual DbSet<SLA> SLAs { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<StatusTimer> StatusTimers { get; set; }
        public virtual DbSet<StatusType> StatusTypes { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Task> Tasks { get; set; }
        public virtual DbSet<TicketLog> TicketLogs { get; set; }
        public virtual DbSet<TicketMsg> TicketMsgs { get; set; }
        public virtual DbSet<Ticket> Tickets { get; set; }
        public virtual DbSet<Timer> Timers { get; set; }
        public virtual DbSet<Type> Types { get; set; }
        public virtual DbSet<Urgency> Urgencies { get; set; }
        public virtual DbSet<UserGroup> UserGroups { get; set; }
        public virtual DbSet<UserRole> UserRoles { get; set; }
        public virtual DbSet<UserRouting> UserRoutings { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UserType> UserTypes { get; set; }
    }
}
