//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartHup.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SMARTEntities : DbContext
    {
        public SMARTEntities()
            : base("name=SMARTEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<ACCOUNT> ACCOUNT { get; set; }
        public virtual DbSet<Action> Action { get; set; }
        public virtual DbSet<ADMINUSER> ADMINUSER { get; set; }
        public virtual DbSet<ALERT> ALERT { get; set; }
        public virtual DbSet<ALERTLEVEL> ALERTLEVEL { get; set; }
        public virtual DbSet<AuditingLog> AuditingLog { get; set; }
        public virtual DbSet<Bank> Bank { get; set; }
        public virtual DbSet<Banks> Banks { get; set; }
        public virtual DbSet<branches> branches { get; set; }
        public virtual DbSet<Channel> Channel { get; set; }
        public virtual DbSet<ChannelType> ChannelType { get; set; }
        public virtual DbSet<City> City { get; set; }
        public virtual DbSet<Contracts> Contracts { get; set; }
        public virtual DbSet<ContractTypes> ContractTypes { get; set; }
        public virtual DbSet<Currency> Currency { get; set; }
        public virtual DbSet<customer> customer { get; set; }
        public virtual DbSet<EntityStatus> EntityStatus { get; set; }
        public virtual DbSet<Favourite> Favourite { get; set; }
        public virtual DbSet<LT_Channel_Service> LT_Channel_Service { get; set; }
        public virtual DbSet<LT_PaymentMethod_Channel> LT_PaymentMethod_Channel { get; set; }
        public virtual DbSet<LT_PaymentMethod_Service> LT_PaymentMethod_Service { get; set; }
        public virtual DbSet<Module> Module { get; set; }
        public virtual DbSet<MONITORINGJOB> MONITORINGJOB { get; set; }
        public virtual DbSet<MONITORINGLOG> MONITORINGLOG { get; set; }
        public virtual DbSet<MONITORINGLOG_ARC> MONITORINGLOG_ARC { get; set; }
        public virtual DbSet<MultiValueList> MultiValueList { get; set; }
        public virtual DbSet<NotificationCategory> NotificationCategory { get; set; }
        public virtual DbSet<NotificationGroup> NotificationGroup { get; set; }
        public virtual DbSet<PaymentField> PaymentField { get; set; }
        public virtual DbSet<PaymentHandler> PaymentHandler { get; set; }
        public virtual DbSet<PaymentMethod> PaymentMethod { get; set; }
        public virtual DbSet<PaymentMethodType> PaymentMethodType { get; set; }
        public virtual DbSet<PaymentProvider> PaymentProvider { get; set; }
        public virtual DbSet<QRTZ_BLOB_TRIGGERS> QRTZ_BLOB_TRIGGERS { get; set; }
        public virtual DbSet<QRTZ_CALENDARS> QRTZ_CALENDARS { get; set; }
        public virtual DbSet<QRTZ_CRON_TRIGGERS> QRTZ_CRON_TRIGGERS { get; set; }
        public virtual DbSet<QRTZ_FIRED_TRIGGERS> QRTZ_FIRED_TRIGGERS { get; set; }
        public virtual DbSet<QRTZ_JOB_DETAILS> QRTZ_JOB_DETAILS { get; set; }
        public virtual DbSet<QRTZ_LOCKS> QRTZ_LOCKS { get; set; }
        public virtual DbSet<QRTZ_PAUSED_TRIGGER_GRPS> QRTZ_PAUSED_TRIGGER_GRPS { get; set; }
        public virtual DbSet<QRTZ_SCHEDULER_STATE> QRTZ_SCHEDULER_STATE { get; set; }
        public virtual DbSet<QRTZ_SIMPLE_TRIGGERS> QRTZ_SIMPLE_TRIGGERS { get; set; }
        public virtual DbSet<QRTZ_SIMPROP_TRIGGERS> QRTZ_SIMPROP_TRIGGERS { get; set; }
        public virtual DbSet<QRTZ_TRIGGERS> QRTZ_TRIGGERS { get; set; }
        public virtual DbSet<RangType> RangType { get; set; }
        public virtual DbSet<REASON> REASON { get; set; }
        public virtual DbSet<RemoteSettings> RemoteSettings { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<RoleActions> RoleActions { get; set; }
        public virtual DbSet<Service> Service { get; set; }
        public virtual DbSet<ServiceField> ServiceField { get; set; }
        public virtual DbSet<ServiceHandler> ServiceHandler { get; set; }
        public virtual DbSet<ServiceProvider> ServiceProvider { get; set; }
        public virtual DbSet<ServiceProviderType> ServiceProviderType { get; set; }
        public virtual DbSet<ServiceScenario> ServiceScenario { get; set; }
        public virtual DbSet<ServiceType> ServiceType { get; set; }
        public virtual DbSet<State> State { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<SystemResponse> SystemResponse { get; set; }
        public virtual DbSet<Termianl_Log> Termianl_Log { get; set; }
        public virtual DbSet<Terminal> Terminal { get; set; }
        public virtual DbSet<TerminalActivities> TerminalActivities { get; set; }
        public virtual DbSet<TerminalComponent> TerminalComponent { get; set; }
        public virtual DbSet<TerminalFamily> TerminalFamily { get; set; }
        public virtual DbSet<TerminalState> TerminalState { get; set; }
        public virtual DbSet<TerminalStatus> TerminalStatus { get; set; }
        public virtual DbSet<TerminalStatusDictionary> TerminalStatusDictionary { get; set; }
        public virtual DbSet<Transaction> Transaction { get; set; }
        public virtual DbSet<Transaction_ARC> Transaction_ARC { get; set; }
        public virtual DbSet<TransactionLog> TransactionLog { get; set; }
        public virtual DbSet<Transactions> Transactions { get; set; }
        public virtual DbSet<Transactions1> Transactions1 { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<UserClaims> UserClaims { get; set; }
        public virtual DbSet<UserLogins> UserLogins { get; set; }
        public virtual DbSet<UserRoles> UserRoles { get; set; }
        public virtual DbSet<Vendor> Vendor { get; set; }
        public virtual DbSet<BillInfo> BillInfo { get; set; }
        public virtual DbSet<PaymentFields> PaymentFields { get; set; }
        public virtual DbSet<Query> Query { get; set; }
    }
}
