//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartHup.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MONITORINGJOB
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MONITORINGJOB()
        {
            this.ALERTLEVEL = new HashSet<ALERTLEVEL>();
            this.MONITORINGLOG = new HashSet<MONITORINGLOG>();
        }
    
        public long systemId { get; set; }
        public int Version { get; set; }
        public string STATUS { get; set; }
        public string Notes { get; set; }
        public string JOBID { get; set; }
        public string JOBNAME { get; set; }
        public Nullable<decimal> MONITOREDENTITYID { get; set; }
        public string CHECKTYPE { get; set; }
        public string CHECKTYPEPARAMETER { get; set; }
        public string MONITORINGSTRING { get; set; }
        public string cronExpression { get; set; }
        public string jobStatus { get; set; }
        public Nullable<decimal> linkId { get; set; }
        public Nullable<long> moduleid { get; set; }
        public Nullable<long> notificationGroupId { get; set; }
        public Nullable<int> entityStatus_systemId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ALERTLEVEL> ALERTLEVEL { get; set; }
        public virtual EntityStatus EntityStatus { get; set; }
        public virtual Module Module { get; set; }
        public virtual NotificationGroup NotificationGroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MONITORINGLOG> MONITORINGLOG { get; set; }
    }
}
