//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartHup.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MONITORINGLOG_ARC
    {
        public long systemId { get; set; }
        public Nullable<int> Version { get; set; }
        public string STATUS { get; set; }
        public string Notes { get; set; }
        public Nullable<long> JOBID { get; set; }
        public Nullable<System.DateTime> MONITORINGTIME { get; set; }
        public Nullable<long> roleId { get; set; }
        public Nullable<long> spId { get; set; }
        public Nullable<long> alertId { get; set; }
        public Nullable<long> userId { get; set; }
        public Nullable<bool> isRead { get; set; }
        public string MONITORINGRESULT { get; set; }
        public Nullable<long> objectId { get; set; }
        public Nullable<long> moduleId { get; set; }
        public string result { get; set; }
        public Nullable<int> entityStatus_systemId { get; set; }
    }
}
