//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartHup.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MultiValueList
    {
        public long systemId { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<System.DateTime> creationDate { get; set; }
        public Nullable<System.DateTime> modificationDate { get; set; }
        public Nullable<long> modifiedBy { get; set; }
        public Nullable<long> createdBy { get; set; }
        public Nullable<int> version { get; set; }
        public string multivalueId { get; set; }
        public string multivalueName { get; set; }
        public string multivalueEName { get; set; }
        public Nullable<long> paymentFieldId { get; set; }
        public Nullable<long> serviceFieldId { get; set; }
    
        public virtual PaymentField PaymentField { get; set; }
        public virtual ServiceField ServiceField { get; set; }
    }
}
