//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartHup.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentMethod
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PaymentMethod()
        {
            this.LT_PaymentMethod_Channel = new HashSet<LT_PaymentMethod_Channel>();
            this.LT_PaymentMethod_Service = new HashSet<LT_PaymentMethod_Service>();
            this.PaymentField = new HashSet<PaymentField>();
            this.PaymentHandler = new HashSet<PaymentHandler>();
            this.Transaction_ARC = new HashSet<Transaction_ARC>();
            this.Transaction = new HashSet<Transaction>();
        }
    
        public long systemId { get; set; }
        public int status { get; set; }
        public System.DateTime creationDate { get; set; }
        public Nullable<System.DateTime> modificationDate { get; set; }
        public long createdBy { get; set; }
        public Nullable<long> modifiedBy { get; set; }
        public int version { get; set; }
        public string paymentMethodId { get; set; }
        public string paymentMethodName { get; set; }
        public string paymentMethodStatus { get; set; }
        public string paymentMethodUIEName { get; set; }
        public string paymentMethodUIName { get; set; }
        public Nullable<long> paymentMethodTypeId { get; set; }
        public Nullable<long> paymentProviderId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LT_PaymentMethod_Channel> LT_PaymentMethod_Channel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LT_PaymentMethod_Service> LT_PaymentMethod_Service { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaymentField> PaymentField { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaymentHandler> PaymentHandler { get; set; }
        public virtual PaymentProvider PaymentProvider { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transaction_ARC> Transaction_ARC { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transaction> Transaction { get; set; }
        public virtual PaymentMethodType PaymentMethodType { get; set; }
    }
}
