//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartHup.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentField
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PaymentField()
        {
            this.MultiValueList = new HashSet<MultiValueList>();
        }
    
        public long systemId { get; set; }
        public int status { get; set; }
        public System.DateTime creationDate { get; set; }
        public Nullable<System.DateTime> modificationDate { get; set; }
        public long createdBy { get; set; }
        public Nullable<long> modifiedBy { get; set; }
        public int version { get; set; }
        public string paymentFieldId { get; set; }
        public string paymentFieldName { get; set; }
        public string paymentFieldStatus { get; set; }
        public string channelFieldEName { get; set; }
        public string channelFieldName { get; set; }
        public string paymentHandlerFieldName { get; set; }
        public string regularExpression { get; set; }
        public Nullable<bool> isRequired { get; set; }
        public Nullable<bool> isResponseField { get; set; }
        public Nullable<bool> isRequestField { get; set; }
        public Nullable<bool> isSavable { get; set; }
        public Nullable<long> additionalFieldName { get; set; }
        public string dateFormat { get; set; }
        public Nullable<long> paymentMethodId { get; set; }
        public Nullable<long> paymentHandlerId { get; set; }
        public Nullable<bool> isPaymentInfo { get; set; }
        public Nullable<int> paymentInfoOrder { get; set; }
        public string dbColumnName { get; set; }
        public Nullable<bool> isCheckable { get; set; }
        public Nullable<bool> isAccount { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MultiValueList> MultiValueList { get; set; }
        public virtual PaymentHandler PaymentHandler { get; set; }
        public virtual PaymentMethod PaymentMethod { get; set; }
    }
}
