//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartHup.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentHandler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PaymentHandler()
        {
            this.PaymentField = new HashSet<PaymentField>();
        }
    
        public long systemId { get; set; }
        public int status { get; set; }
        public System.DateTime creationDate { get; set; }
        public Nullable<System.DateTime> modificationDate { get; set; }
        public long createdBy { get; set; }
        public Nullable<long> modifiedBy { get; set; }
        public int version { get; set; }
        public string paymentHandlerId { get; set; }
        public string paymentHandlerName { get; set; }
        public string paymentHandlerStatus { get; set; }
        public long paymentMethodId { get; set; }
        public string paymentHostUri { get; set; }
        public string paymentHostIntegrationType { get; set; }
        public string paymentHostCharSet { get; set; }
        public Nullable<bool> isSslExist { get; set; }
        public string paymentHostPublicKey { get; set; }
        public string paymentHostEncryptionMethod { get; set; }
        public string paymentHostAcceptEncoding { get; set; }
        public string paymentHostContentType { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaymentField> PaymentField { get; set; }
        public virtual PaymentMethod PaymentMethod { get; set; }
    }
}
