//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartHup.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Query
    {
        public long systemId { get; set; }
        public int status { get; set; }
        public System.DateTime creationDate { get; set; }
        public Nullable<System.DateTime> modificationDate { get; set; }
        public long createdBy { get; set; }
        public Nullable<long> modifiedBy { get; set; }
        public int version { get; set; }
        public string serviceFieldId { get; set; }
        public string serviceFieldName { get; set; }
        public string serviceFieldStatus { get; set; }
        public string channelFieldEName { get; set; }
        public string channelFieldName { get; set; }
        public string serviceHandlerFieldName { get; set; }
        public string regularExpression { get; set; }
        public Nullable<bool> isRequired { get; set; }
        public string dateFormat { get; set; }
        public Nullable<bool> isRequestField { get; set; }
        public Nullable<bool> isSavable { get; set; }
        public Nullable<bool> isResponseField { get; set; }
        public Nullable<long> additionalFieldName { get; set; }
        public Nullable<long> serviceId { get; set; }
        public Nullable<long> serviceHanlerId { get; set; }
        public Nullable<bool> isParent { get; set; }
        public Nullable<long> ParentId { get; set; }
        public Nullable<bool> isPaymentInfo { get; set; }
        public Nullable<int> paymentInfoOrder { get; set; }
        public Nullable<long> regTypeId { get; set; }
    }
}
