//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartHup.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reminder
    {
        public long systemId { get; set; }
        public string ReminderName { get; set; }
        public string Notification { get; set; }
        public Nullable<int> alertBefore { get; set; }
        public string alertTime { get; set; }
        public Nullable<long> UserId { get; set; }
    
        public virtual User User { get; set; }
    }
}
