//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartHup.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoleActions
    {
        public long systemId { get; set; }
        public long RoleId { get; set; }
        public long actionId { get; set; }
        public System.DateTime creationDate { get; set; }
        public Nullable<System.DateTime> modificationDate { get; set; }
        public Nullable<System.DateTime> deletedDate { get; set; }
        public int status { get; set; }
        public int version { get; set; }
        public Nullable<int> entityStatus_systemId { get; set; }
        public long createdBy { get; set; }
        public Nullable<long> modifiedBy { get; set; }
        public Nullable<long> deletedBy { get; set; }
    
        public virtual Action Action { get; set; }
        public virtual EntityStatus EntityStatus { get; set; }
        public virtual Role Role { get; set; }
    }
}
