//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartHup.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoutingRule
    {
        public long systemId { get; set; }
        public string RoutingRuleName { get; set; }
        public string RoutingRuleArName { get; set; }
        public Nullable<long> SubmitterGroupID { get; set; }
        public Nullable<long> AssignedGroupID { get; set; }
        public Nullable<long> CategoryID { get; set; }
        public Nullable<long> SLAID { get; set; }
        public System.DateTime creationDate { get; set; }
        public Nullable<System.DateTime> modificationDate { get; set; }
        public long createdBy { get; set; }
        public Nullable<long> modifiedBy { get; set; }
        public int version { get; set; }
        public Nullable<int> entityStatus_systemId { get; set; }
        public Nullable<long> SubCategory { get; set; }
        public Nullable<long> AssignedUser { get; set; }
        public Nullable<System.DateTime> deletedDate { get; set; }
        public Nullable<long> deletedBy { get; set; }
    
        public virtual EntityStatu EntityStatu { get; set; }
        public virtual EntityStatu EntityStatu1 { get; set; }
        public virtual SLA SLA { get; set; }
        public virtual UserGroup UserGroup { get; set; }
        public virtual UserGroup UserGroup1 { get; set; }
        public virtual User User { get; set; }
    }
}
