//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartHup.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Service()
        {
            this.LT_Channel_Service = new HashSet<LT_Channel_Service>();
            this.LT_PaymentMethod_Service = new HashSet<LT_PaymentMethod_Service>();
            this.Service1 = new HashSet<Service>();
            this.Service11 = new HashSet<Service>();
            this.ServiceField = new HashSet<ServiceField>();
            this.ServiceHandler = new HashSet<ServiceHandler>();
            this.Transaction_ARC = new HashSet<Transaction_ARC>();
            this.Transaction = new HashSet<Transaction>();
            this.Service12 = new HashSet<Service>();
        }
    
        public long systemId { get; set; }
        public int status { get; set; }
        public System.DateTime creationDate { get; set; }
        public Nullable<System.DateTime> modificationDate { get; set; }
        public long createdBy { get; set; }
        public Nullable<long> modifiedBy { get; set; }
        public int version { get; set; }
        public string serviceId { get; set; }
        public string serviceName { get; set; }
        public string serviceEName { get; set; }
        public string ServiceLable { get; set; }
        public string ServiceELable { get; set; }
        public string serviceStatus { get; set; }
        public string serviceDescription { get; set; }
        public Nullable<bool> isParent { get; set; }
        public Nullable<long> serviceConfigurationId { get; set; }
        public long serviceProviderId { get; set; }
        public Nullable<bool> precheckRquired { get; set; }
        public Nullable<long> serviceScenarioId { get; set; }
        public Nullable<long> precheckServiceId { get; set; }
        public Nullable<long> parentId { get; set; }
        public Nullable<System.DateTime> Note { get; set; }
        public string paymentListName { get; set; }
        public string inquiryListName { get; set; }
        public Nullable<System.DateTime> deletedDate { get; set; }
        public Nullable<long> deletedBy { get; set; }
        public Nullable<int> entityStatus_systemId { get; set; }
        public Nullable<long> serviceTypeId { get; set; }
        public Nullable<long> paymentServiceId { get; set; }
        public string serviceDescriptionAr { get; set; }
        public Nullable<bool> loadingAllFields { get; set; }
    
        public virtual EntityStatus EntityStatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LT_Channel_Service> LT_Channel_Service { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LT_PaymentMethod_Service> LT_PaymentMethod_Service { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Service> Service1 { get; set; }
        public virtual Service Service2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Service> Service11 { get; set; }
        public virtual Service Service3 { get; set; }
        public virtual ServiceProvider ServiceProvider { get; set; }
        public virtual ServiceScenario ServiceScenario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiceField> ServiceField { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiceHandler> ServiceHandler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transaction_ARC> Transaction_ARC { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transaction> Transaction { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Service> Service12 { get; set; }
        public virtual Service Service4 { get; set; }
        public virtual ServiceType ServiceType { get; set; }
    }
}
