//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartHup.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceScenario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ServiceScenario()
        {
            this.Service = new HashSet<Service>();
        }
    
        public long systemId { get; set; }
        public int status { get; set; }
        public System.DateTime creationDate { get; set; }
        public Nullable<System.DateTime> modificationDate { get; set; }
        public long createdBy { get; set; }
        public Nullable<long> modifiedBy { get; set; }
        public int version { get; set; }
        public string serviceScenarioId { get; set; }
        public string serviceScenarioName { get; set; }
        public string serviceScenarioStatus { get; set; }
        public bool paymentProviderHandler { get; set; }
        public bool serviceProviderHandler { get; set; }
        public Nullable<bool> serviceProviderAcknowledge { get; set; }
        public Nullable<bool> serviceProviderProvision { get; set; }
        public Nullable<bool> serviceProviderInquiry { get; set; }
        public Nullable<bool> paymentProviderInquiry { get; set; }
        public Nullable<bool> paymentProviderPayment { get; set; }
        public Nullable<bool> paymentProviderPaymentCredit { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Service> Service { get; set; }
    }
}
