//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartHup.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceHandler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ServiceHandler()
        {
            this.ServiceField = new HashSet<ServiceField>();
        }
    
        public long systemId { get; set; }
        public int status { get; set; }
        public System.DateTime creationDate { get; set; }
        public Nullable<System.DateTime> modificationDate { get; set; }
        public long createdBy { get; set; }
        public Nullable<long> modifiedBy { get; set; }
        public int version { get; set; }
        public string serviceHanlerId { get; set; }
        public string serviceHanlerName { get; set; }
        public string serviceHanlerStatus { get; set; }
        public long serviceId { get; set; }
        public string serviceHostUri { get; set; }
        public string serviceHostIntegrationType { get; set; }
        public string serviceHostCharSet { get; set; }
        public Nullable<bool> isSslExist { get; set; }
        public string serviceHostPublicKey { get; set; }
        public string serviceHostEncryptionMethod { get; set; }
        public string serviceHostAcceptEncoding { get; set; }
        public string serviceHostContentType { get; set; }
        public Nullable<System.DateTime> deletedDate { get; set; }
        public Nullable<long> deletedBy { get; set; }
        public Nullable<int> entityStatus_systemId { get; set; }
    
        public virtual EntityStatus EntityStatus { get; set; }
        public virtual Service Service { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiceField> ServiceField { get; set; }
    }
}
