//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartHup.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Status
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Status()
        {
            this.EscalationRules = new HashSet<EscalationRule>();
            this.EscalationRules1 = new HashSet<EscalationRule>();
            this.StatusTimers = new HashSet<StatusTimer>();
            this.Tasks1 = new HashSet<Task>();
            this.Tickets1 = new HashSet<Ticket>();
            this.Timers = new HashSet<Timer>();
        }
    
        public long systemId { get; set; }
        public string StatusName { get; set; }
        public string StatusArName { get; set; }
        public string Description { get; set; }
        public Nullable<long> StatusType_ID { get; set; }
        public Nullable<bool> IsDefault { get; set; }
        public Nullable<bool> Tickets { get; set; }
        public Nullable<bool> Tasks { get; set; }
        public Nullable<long> createdBy { get; set; }
        public Nullable<long> modifiedBy { get; set; }
        public Nullable<long> deletedBy { get; set; }
        public Nullable<System.DateTime> creationDate { get; set; }
        public Nullable<System.DateTime> modificationDate { get; set; }
        public Nullable<System.DateTime> deletedDate { get; set; }
        public Nullable<int> entityStatus_systemId { get; set; }
        public Nullable<int> version { get; set; }
    
        public virtual EntityStatu EntityStatu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EscalationRule> EscalationRules { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EscalationRule> EscalationRules1 { get; set; }
        public virtual StatusType StatusType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StatusTimer> StatusTimers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Task> Tasks1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ticket> Tickets1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Timer> Timers { get; set; }
    }
}
