//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartHup.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StatusTimer
    {
        public long systemId { get; set; }
        public System.DateTime Time { get; set; }
        public long Status_ID { get; set; }
        public long Timer_ID { get; set; }
    
        public virtual Status Status { get; set; }
        public virtual Timer Timer { get; set; }
    }
}
