//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartHup.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Termianl_Log
    {
        public long systemId { get; set; }
        public string TL_Name { get; set; }
        public int status { get; set; }
        public System.DateTime creationDate { get; set; }
        public Nullable<System.DateTime> modificationDate { get; set; }
        public long createdBy { get; set; }
        public Nullable<long> modifiedBy { get; set; }
        public Nullable<int> version { get; set; }
        public Nullable<long> terId { get; set; }
        public long PACKNO { get; set; }
        public string EX_ter_ID { get; set; }
        public string ter_NAME { get; set; }
        public Nullable<System.DateTime> STOP_TIME { get; set; }
        public Nullable<System.DateTime> START_TIME { get; set; }
        public long REASON_CODE { get; set; }
        public long ter_STATUS { get; set; }
        public Nullable<long> NOTIFIED { get; set; }
        public Nullable<long> VALID_CASE { get; set; }
        public Nullable<long> NOTIFICATION_PERIOD { get; set; }
        public Nullable<long> DOWN_TIME { get; set; }
        public string serialNo { get; set; }
        public Nullable<long> componentId { get; set; }
        public string messageCode { get; set; }
        public Nullable<long> termianlStatus { get; set; }
        public Nullable<long> termianlState { get; set; }
        public string additionalF1 { get; set; }
        public string additionalF2 { get; set; }
        public string additionalF3 { get; set; }
    
        public virtual EntityStatus EntityStatus { get; set; }
        public virtual REASON REASON { get; set; }
        public virtual Terminal Terminal { get; set; }
        public virtual TerminalComponent TerminalComponent { get; set; }
        public virtual TerminalState TerminalState { get; set; }
        public virtual TerminalStatusDictionary TerminalStatusDictionary { get; set; }
    }
}
