//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartHup.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Terminal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Terminal()
        {
            this.Termianl_Log = new HashSet<Termianl_Log>();
            this.Transaction_ARC = new HashSet<Transaction_ARC>();
            this.Transaction = new HashSet<Transaction>();
            this.TerminalActivities = new HashSet<TerminalActivities>();
            this.TerminalStatus1 = new HashSet<TerminalStatus>();
        }
    
        public long systemId { get; set; }
        public int status { get; set; }
        public System.DateTime creationDate { get; set; }
        public Nullable<System.DateTime> modificationDate { get; set; }
        public long createdBy { get; set; }
        public Nullable<long> modifiedBy { get; set; }
        public int version { get; set; }
        public Nullable<long> terminalId { get; set; }
        public string terminalName { get; set; }
        public string terminalStatus { get; set; }
        public string terminalIP { get; set; }
        public string serialNumber { get; set; }
        public string terminalModel { get; set; }
        public string address { get; set; }
        public string street { get; set; }
        public string terminalCode { get; set; }
        public string workingKey { get; set; }
        public string attitude { get; set; }
        public string latitude { get; set; }
        public Nullable<long> terminalFamilyId { get; set; }
        public long stateId { get; set; }
        public long cityId { get; set; }
        public Nullable<long> vendorId { get; set; }
        public long bankId { get; set; }
        public string terminalPassword { get; set; }
        public Nullable<long> channelId { get; set; }
        public string terminalUserName { get; set; }
    
        public virtual Bank Bank { get; set; }
        public virtual Channel Channel { get; set; }
        public virtual City City { get; set; }
        public virtual EntityStatus EntityStatus { get; set; }
        public virtual State State { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Termianl_Log> Termianl_Log { get; set; }
        public virtual TerminalFamily TerminalFamily { get; set; }
        public virtual Vendor Vendor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transaction_ARC> Transaction_ARC { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transaction> Transaction { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TerminalActivities> TerminalActivities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TerminalStatus> TerminalStatus1 { get; set; }
    }
}
