//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartHup.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TerminalStatus
    {
        public long systemId { get; set; }
        public string tsName { get; set; }
        public int status { get; set; }
        public System.DateTime creationDate { get; set; }
        public Nullable<System.DateTime> modificationDate { get; set; }
        public long createdBy { get; set; }
        public Nullable<long> modifiedBy { get; set; }
        public Nullable<int> version { get; set; }
        public Nullable<long> terId { get; set; }
        public Nullable<long> clientID { get; set; }
        public Nullable<long> termianlId { get; set; }
        public string serialNo { get; set; }
        public Nullable<long> componentId { get; set; }
        public string messageCode { get; set; }
        public string notices { get; set; }
        public Nullable<System.DateTime> eventTime { get; set; }
        public Nullable<long> termianlStatus { get; set; }
        public Nullable<long> termianlState { get; set; }
        public Nullable<long> reasonCode { get; set; }
    
        public virtual REASON REASON { get; set; }
        public virtual Terminal Terminal { get; set; }
        public virtual TerminalComponent TerminalComponent { get; set; }
        public virtual TerminalState TerminalState { get; set; }
        public virtual TerminalStatusDictionary TerminalStatusDictionary { get; set; }
    }
}
