//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartHup.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionLog
    {
        public decimal SystemId { get; set; }
        public int Version { get; set; }
        public string Status { get; set; }
        public string Note { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
        public string tranDateTime { get; set; }
        public string applicationId { get; set; }
        public string UUID { get; set; }
        public string DISCRIMINATOR { get; set; }
        public Nullable<int> responseCode { get; set; }
        public string responseMessage { get; set; }
        public string responseStatus { get; set; }
        public string PAN { get; set; }
        public string expDate { get; set; }
        public string fromAccountType { get; set; }
        public string accountCurrency { get; set; }
        public string tranCurrency { get; set; }
        public string userName { get; set; }
        public string entityId { get; set; }
        public string entityType { get; set; }
        public string toCard { get; set; }
        public Nullable<double> tranAmount { get; set; }
        public string payeeId { get; set; }
        public string paymentInfo { get; set; }
        public string originalTranUUID { get; set; }
        public string originalTranDateTime { get; set; }
        public string phoneNo { get; set; }
        public string email { get; set; }
        public string mbr { get; set; }
        public string registrationType { get; set; }
        public string authenticationType { get; set; }
        public string serviceProviderId { get; set; }
        public string serviceInfo { get; set; }
    }
}
