//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartHup.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Transaction()
        {
            this.Transaction1 = new HashSet<Transaction>();
        }
    
        public long systemId { get; set; }
        public Nullable<int> status { get; set; }
        public string transactionLogStatus { get; set; }
        public Nullable<long> transactionId { get; set; }
        public Nullable<System.DateTime> requestDateTime { get; set; }
        public Nullable<System.DateTime> responseDateTime { get; set; }
        public Nullable<long> exTranDateTime { get; set; }
        public Nullable<long> packNo { get; set; }
        public Nullable<double> transactionAmount { get; set; }
        public string applicationId { get; set; }
        public string discriminator { get; set; }
        public string responseCode { get; set; }
        public string responseMessage { get; set; }
        public string responseStatus { get; set; }
        public string PAN { get; set; }
        public string MSISDN { get; set; }
        public string bankAccount { get; set; }
        public string expDate { get; set; }
        public string mbr { get; set; }
        public string tranCurrency { get; set; }
        public string UUID { get; set; }
        public string userName { get; set; }
        public string entityId { get; set; }
        public string entityType { get; set; }
        public string toCard { get; set; }
        public string fromAccountType { get; set; }
        public string fromAccount { get; set; }
        public string toAccountType { get; set; }
        public string toAccount { get; set; }
        public string accountCurrency { get; set; }
        public string paymentInfo { get; set; }
        public string originalTranUUID { get; set; }
        public Nullable<long> originalTranID { get; set; }
        public string phoneNo { get; set; }
        public string email { get; set; }
        public string registrationType { get; set; }
        public string authenticationType { get; set; }
        public string customerRefrence { get; set; }
        public string transactionState { get; set; }
        public Nullable<double> transactionFees { get; set; }
        public Nullable<double> customerBalance { get; set; }
        public string reciptNo { get; set; }
        public string note { get; set; }
        public string payeeId { get; set; }
        public Nullable<long> systemResponseId { get; set; }
        public Nullable<long> exSystemResponseId { get; set; }
        public Nullable<long> paymentMethodId { get; set; }
        public Nullable<long> channelId { get; set; }
        public Nullable<long> paymentProviderId { get; set; }
        public Nullable<long> currencyId { get; set; }
        public Nullable<long> serviceId { get; set; }
        public Nullable<long> serviceProviderId { get; set; }
        public Nullable<long> customerId { get; set; }
        public Nullable<long> customerCardId { get; set; }
        public Nullable<long> terminalId { get; set; }
        public string additional_8_Field_1 { get; set; }
        public string additional_8_Field_2 { get; set; }
        public string additional_8_Field_3 { get; set; }
        public string additional_16_Field_1 { get; set; }
        public string additional_16_Field_2 { get; set; }
        public string additional_16_Field_3 { get; set; }
        public string additional_32_Field_1 { get; set; }
        public string additional_32_Field_2 { get; set; }
        public string additional_32_Field_3 { get; set; }
        public string additional_128_Field_1 { get; set; }
        public string additional_128_Field_2 { get; set; }
        public string additional_256_Field_1 { get; set; }
        public string additional_256_Field_2 { get; set; }
        public string additional_512_Field_1 { get; set; }
        public Nullable<long> serviceNum { get; set; }
        public Nullable<long> channelNum { get; set; }
        public Nullable<long> paymentMethodNum { get; set; }
        public string workingKey { get; set; }
        public string BANKCODE { get; set; }
        public string miniStatementRecords { get; set; }
    
        public virtual Currency Currency { get; set; }
        public virtual PaymentMethod PaymentMethod { get; set; }
        public virtual PaymentProvider PaymentProvider { get; set; }
        public virtual Service Service { get; set; }
        public virtual SystemResponse SystemResponse { get; set; }
        public virtual Terminal Terminal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transaction> Transaction1 { get; set; }
        public virtual Transaction Transaction2 { get; set; }
    }
}
