//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartHup.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Type
    {
        public long systemId { get; set; }
        public string TypeName { get; set; }
        public string TypeArName { get; set; }
        public Nullable<int> entityStatus_systemId { get; set; }
    }
}
